### ISSUE TITLE
Charts with a bottom legend are missing padding

### ISSUE THREAD

**Issue by erundle** [maseh87/c3-chart#11]
Right now the legend is right against the bottom of the chart. It needs 5px of spacing between the end of the chart and the start of the legend

**Comment by erundle** [comment]
It looks like the issue is in c3 chart. I will put in a pull request there. Closing

**Comment by erundle** [comment]
If you updated to the latest c3 0.4.11-rc1 the issue is already fixed there

**Comment by maseh87** [comment]
sounds great! thanks!
