### ISSUE TITLE
Unable to bind chart to element when charts are used in directives

### ISSUE THREAD

**Issue by jeff-phillips-18** [maseh87/c3-chart#9]
I created a directive that contains a c3-chart and I have multiples of these directives on a page. For the binding to work I have to set the ID of the c3-chart directive in the controller for my directive. Basically, I am appending 'myChart' to an ID that is passed to my directive. However, when I do this the chart is not drawn and it's due to d3_select not finding the element.

I have found that by putting the c3.generate and c3Factory.register calls in the c3Chart directive in a timeout function my charts are bound and hence drawn correctly.

**Comment by maseh87** [comment]
Great find and thanks for the fix!
